version: "3.2"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=general-user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=al-order
    ports:
      - target: 3306
        published: 3306
        mode: host    
  redis:
    image: redis:4.0.14
    ports:
      - target: 6379
        published: 6379
        mode: host
  al-order:
    env_file:
      - .env
    environment:
      HTTPS_PROXY: http://192.168.1.106:1080
      HTTP_PROXY: http://192.68.1.106:1080
    build:
      context: .
    ports:
      - target: 8080
        published: 8080
        mode: host
    depends_on:
      - mysql
      - redis
    entrypoint: /bin/alorder
    command: "-sqlFile /bin/sql/up.sql -host 0.0.0.0"