version: "3.2"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=general-user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=al-order
    ports:
      - target: 3306
        published: 3862
        mode: host
  redis:
    image: redis:4.0.14
    ports:
      - target: 6379
        published: 6379
        mode: host 
  al-order:
    build:
      context: .
    ports:
      - target: 8080
        published: 8080
        mode: host
    depends_on:
      - mysql
      - redis